parameters:
#    brasa_seguridad.example.class: Brasa\SeguridadBundle\Example

services:
#    brasa_seguridad.example:
#        class: %brasa_seguridad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
