contabilidad:
    resource: "@ContabilidadBundle/Controller/"
    type:     annotation
    prefix:   /

inventario:
    resource: "@InventarioBundle/Controller/"
    type:     annotation
    prefix:   /

citas:
    resource: "@CitasBundle/Controller/"
    type:     annotation
    prefix:   /
