empleado:
    resource: "@EmpleadoBundle/Controller/"
    type:     annotation
    prefix:   /

general:
    resource: "@GeneralBundle/Controller/"
    type:     annotation
    prefix:   /

genereal:
    resource: "@SeguridadBundle/Controller/"
    type:     annotation
    prefix:   /

contabilidad:
    resource: "@ContabilidadBundle/Controller/"
    type:     annotation
    prefix:   /

inventario:
    resource: "@InventarioBundle/Controller/"
    type:     annotation
    prefix:   /

citas:
    resource: "@CitasBundle/Controller/"
    type:     annotation
    prefix:   /

