empleado:
    resource: "@EmpleadoBundle/Controller/"
    type:     annotation
    prefix:   /

general:
    resource: "@GeneralBundle/Controller/"
    type:     annotation
    prefix:   /

seguridad:
    resource: "@SeguridadBundle/Controller/"
    type:     annotation
    prefix:   /

contabilidad:
    resource: "@ContabilidadBundle/Controller/"
    type:     annotation
    prefix:   /

inventario:
    resource: "@InventarioBundle/Controller/"
    type:     annotation
    prefix:   /

citas:
    resource: "@CitasBundle/Controller/"
    type:     annotation
    prefix:   /
    
factura:
    resource: "@FacturacionBundle/Controller/"
    type:     annotation
    prefix:   /

