security:
    encoders:
        SeguridadBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
 
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
 
    providers:
        user_db:
            entity: { class: SeguridadBundle\Entity\User, property: username }
 
    firewalls:
        main:
            pattern: /.*
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login
                remember_me: true
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true
            
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: /todos, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin, roles: ROLE_ADMIN }
        - { path: /.*, roles: ROLE_USER }        
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }