<?php

namespace SeguridadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SegDocumentoRepository extends EntityRepository {
    
    public function listaDql($strTipo = "", $strModulo = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT s FROM SeguridadBundle:SegDocumento s WHERE s.codigoDocumentoPk <> 0";
        
        if($strTipo != "") {
            $dql .= " AND s.tipo LIKE '%" . $strTipo . "%'";
        }
        if ($strModulo != ""){
            $dql .= " AND s.modulo LIKE '%" . $strModulo . "%'";
        }
        $dql .= " ORDER BY s.tipo ASC";
        
        return $dql;
    }
    
}