<?php

namespace EmpleadoBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadoRepository extends EntityRepository
{
}
