<?php

namespace SeguridadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function listaDql() {        
        $em = $this->getEntityManager();
        $dql   = "SELECT u FROM SeguridadBundle:User u";
        $dql .= " ORDER BY u.nombreCorto ASC";
        return $dql;
    } 
}