<?php

namespace ContabilidadBundle\Repository;

/**
 * ClaseComprobantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaseComprobantesRepository extends \Doctrine\ORM\EntityRepository
{
}
