<?php

namespace ContabilidadBundle\Repository;

/**
 * ComprobantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprobantesRepository extends \Doctrine\ORM\EntityRepository
{
}
