<?php

namespace ContabilidadBundle\Repository;

/**
 * TarifaIvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifaIvaRepository extends \Doctrine\ORM\EntityRepository
{
}
