<?php

namespace ContabilidadBundle\Repository;

/**
 * TipoComprobantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoComprobantesRepository extends \Doctrine\ORM\EntityRepository
{
}
