<?php

namespace FacturacionBundle\Repository;

/**
 * FacturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaRepository extends \Doctrine\ORM\EntityRepository {

    public function listaDql($strNumeroDocumento = "") {
        $dql = "SELECT f FROM FacturacionBundle:Factura f WHERE f.codigoFacturaPk <> 0 ";
        if ($strNumeroDocumento != "") {
            $dql .= " AND f.numeroDocumento = " . $strNumeroDocumento;
        }
        $dql .= " ORDER BY f.numeroDocumento ASC";
        return $dql;
    }

}
