<?php

namespace FacturacionBundle\Repository;

/**
 * FacturaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaDetalleRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function eliminarSeleccionados($arrSeleccionados) {
        if (count($arrSeleccionados) > 0) {
            $em = $this->getEntityManager();
            foreach ($arrSeleccionados AS $codigo) {
                $arRegistro = $em->getRepository('FacturacionBundle:FacturaDetalle')->find($codigo);
                $em->remove($arRegistro);
            }
            $em->flush();
        }
    }
}
