<?php

namespace FacturacionBundle\Repository;

/**
 * MovimientoFacturaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoFacturaDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
