<?php

namespace CitasBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    public function listaDql($strCitas){
        $em = $this->getEntityManager();
        $dql = "SELECT * FROM citas";
      
    }
    
}
