<?php

namespace CitasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CitasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitasRepository extends EntityRepository {

    public function obtenerCitas() {
        $em = $this->getEntityManager();
        $arCitas = $em->getRepository('CitasBundle:Citas')->findAll();
//        $dql = "SELECT * as citas FROM CitasBundle:Citas";
//        $query = $em->createQuery($dql);
//         $arrayResultado = $query->getResult();
//                $codigoKardexPk = count($arrayResultado);
        if($arCitas > 0) {
            // creamos un array
            $datos = array();

            //guardamos en un array multidimensional todos los datos de la consulta
            $i = 0;

            // Ejecutamos nuestra sentencia sql
            $e = $em->createQuery('SELECT * FROM citas');

            foreach ($arCitas as $arCita) {
                $datos[$i] = $arCita;
                $i++;
            }
//            while ($row = $e->fetch_array()) { // realizamos un ciclo while para traer los eventos encontrados en la base de dato
//                // Alimentamos el array con los datos de los eventos
//            }

            // Transformamos los datos encontrado en la BD al formato JSON
            echo json_encode(
                    array(
                        "success" => 1,
                        "result" => $datos
                    ));
        } else {
            echo "no hay datos";
        }
    }

}
