<?php

namespace CitasBundle\Repository;
use Doctrine\ORM\EntityRepository;


/**
 * CitasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitasRepository extends EntityRepository
{
}
