<?php

namespace CitasBundle\Repository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends \Doctrine\ORM\EntityRepository
{
        public function listaDql($strNit = "", $strNombre = "") {
        $dql   = "SELECT t FROM CitasBundle:Cliente t WHERE t.codigoClientePk <> 0";        
        if($strNit != "") {
            $dql .= " AND t.numDocumento = " . $strNit;
        }
        if($strNombre != "") {
            $dql .= " AND t.primerNombre like '%" . $strNombre. "%'";
        }
        $dql .= " ORDER BY t.primerNombre ASC";
        return $dql;
    } 
}
