<?php

namespace GeneralBundle\Repository;

/**
 * CentroCostoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroCostoRepository extends \Doctrine\ORM\EntityRepository
{
}
