<?php

namespace GeneralBundle\Repository;

/**
 * ClaseComprobantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaseComprobanteRepository extends \Doctrine\ORM\EntityRepository
{
}
