<?php

namespace GeneralBundle\Repository;

/**
 * ComprobantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprobanteRepository extends \Doctrine\ORM\EntityRepository
{
}
