<?php

namespace GeneralBundle\Repository;

use InventarioBundle\Entity\KardexArticulo;
use InventarioBundle\InventarioBundle;

/**
 * ConfiguracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracionRepository extends \Doctrine\ORM\EntityRepository
{

    public function cerrarPeriodo($periodoCierre)
    {
        $em = $this->getEntityManager();
        $arCierre = $em->getRepository('GeneralBundle:Configuracion')->find(1);
        $arArticulos = $em->getRepository('InventarioBundle:Articulo')->findAll();
        $respuesta = "";

        //consuta ultimo cierre inventario en configuracion
        $ultimoCierreInventario = $arCierre->getUltimoCierreInventario();

        // cierre de periodo
        if ($ultimoCierreInventario == $periodoCierre) {

            $respuesta = "periodo ya cerrado";

            foreach ($arArticulos as $articulo) {
                $codigoArticulo = $em->getRepository('InventarioBundle:Articulo')->findOneBy(array('codigoArticuloPk' => $articulo));
                $saldoArticulo = $em->getRepository('InventarioBundle:SaldosArticulos')->findOneBy(array('codigoArticuloFk' => $codigoArticulo, 'periodo' => $periodoCierre));

                if ($codigoArticulo->getManejaKardex() == 1) {

                    if ($saldoArticulo == null) {
                        $this->consultaSaldosKardex($codigoArticulo, $periodoCierre);
                    }
                }
            }
        } else {
            foreach ($arArticulos as $articulo) {
                $codigoArticulo = $em->getRepository('InventarioBundle:Articulo')->findOneBy(array('codigoArticuloPk' => $articulo));
                $saldoArticulo = $em->getRepository('InventarioBundle:SaldosArticulos')->findOneBy(array('codigoArticuloFk' => $codigoArticulo, 'periodo' => $periodoCierre));
                $saldoKardex = $em->getRepository('InventarioBundle:KardexArticulo')->findby(array('codigoArticuloFk' => $codigoArticulo, 'periodoMovimiento' => $periodoCierre));

                if ($codigoArticulo->getManejaKardex() == 1) {

                    if ($saldoArticulo == null) {
                        if ($saldoKardex == null) {
                            $this->ingresarSaldosCero($codigoArticulo, $periodoCierre);
                        }
                    }

                    if ($saldoKardex !== null) {
                        $this->consultaSaldosKardex($codigoArticulo, $periodoCierre);
                    }
                }
            }
            $arCierre->setUltimoCierreInventario($periodoCierre);
            $em->persist($arCierre);
            $em->flush();
        }
        return $respuesta;
    }

    public function consultaSaldosKardex($codigoArticulo, $periodoCierre)
    {
        $em = $this->getEntityManager();
        $saldos = new \InventarioBundle\Entity\SaldosArticulos();
        $articulo = $em->getRepository('InventarioBundle:Articulo')->findOneBy(array('codigoArticuloPk' => $codigoArticulo));
        $codigoArticulo = $articulo->getCodigoArticuloPk();


        $numeroRegistros = count($em->getRepository('InventarioBundle:KardexArticulo')->findBy(array('codigoArticuloFk' => $codigoArticulo, 'periodoMovimiento' => $periodoCierre)));

        if ($numeroRegistros == 0) {
            //insertar valores en cero
            $saldos->setArticuloRel($articulo);
            $saldos->setPeriodo($periodoCierre);
            $saldos->setSaldoInicial('0');
            $saldos->setEntradas('0');
            $saldos->setSalidas('0');
            $saldos->setSaldoFinal('0');
            $saldos->setCostoPromedio('0');
            $saldos->setCostoUnitario('0');
            $saldos->setUltimoCosto('0');
            $em->persist($saldos);
            $em->flush();
        }

        if ($numeroRegistros > 0) {
            $saldos->setArticuloRel($articulo);
            $saldos->setPeriodo($periodoCierre);

            $dql = "SELECT mk.saldoAnterior as kardex FROM InventarioBundle:KardexArticulo mk  "
                . "WHERE mk.codigoArticuloFk = " . $codigoArticulo . " " . "AND mk.periodoMovimiento = " . $periodoCierre
                . " ORDER by mk.fechaMovimiento ASC";
            $query = $em->createQuery($dql);
            $arrayResultado = $query->getResult();
            $saldoInicial = $arrayResultado[0]['kardex'];

            $dql = "SELECT SUM(mk.salidas) as salidas FROM InventarioBundle:KardexArticulo mk  "
                . "WHERE mk.codigoArticuloFk = " . $codigoArticulo . " " . "AND mk.periodoMovimiento = " . $periodoCierre
                . " ORDER by mk.fechaMovimiento ASC";
            $query = $em->createQuery($dql);
            $arrayResultado = $query->getResult();
            $salidas = $arrayResultado[0]['salidas'];

            $dql = "SELECT SUM(mk.entradas) as entradas FROM InventarioBundle:KardexArticulo mk  "
                . "WHERE mk.codigoArticuloFk = " . $codigoArticulo . " " . "AND mk.periodoMovimiento = " . $periodoCierre
                . " ORDER by mk.fechaMovimiento ASC";
            $query = $em->createQuery($dql);
            $arrayResultado = $query->getResult();
            $entradas = $arrayResultado[0]['entradas'];

            $dql = "SELECT mk.costoPromedio as costoPromedio FROM InventarioBundle:KardexArticulo mk  "
                . "WHERE mk.codigoArticuloFk = " . $codigoArticulo . " " . "AND mk.periodoMovimiento = " . $periodoCierre
                . " ORDER by mk.fechaMovimiento DESC";
            $query = $em->createQuery($dql);
            $arrayResultado = $query->getResult();
            $costoPromedio = $arrayResultado[0]['costoPromedio'];

            //insertar saldos
            $saldos->setSaldoInicial($saldoInicial);
            $saldos->setEntradas($entradas);
            $saldos->setSalidas($salidas);
            $saldoFinal = $saldoInicial + $entradas - $salidas;
            $saldos->setSaldoFinal($saldoFinal);
            $saldos->setCostoPromedio($costoPromedio);
            $costoUnitario = $costoPromedio / $saldoFinal;
            $saldos->setCostoUnitario($costoUnitario);
            $saldos->setUltimoCosto('0');
            $em->persist($saldos);
            $em->flush();
        }
    }

    public function ingresarSaldosCero($codigoArticulo, $periodoActual)
    {
        $em = $this->getEntityManager();
        $saldos = new \InventarioBundle\Entity\SaldosArticulos();
        $saldos->setArticuloRel($codigoArticulo);
        $saldos->setPeriodo($periodoActual);
        $saldos->setSaldoInicial('0');
        $saldos->setEntradas('0');
        $saldos->setSalidas('0');
        $saldos->setSaldoFinal('0');
        $saldos->setCostoPromedio('0');
        $saldos->setCostoUnitario('0');
        $saldos->setUltimoCosto('0');
        $em->persist($saldos);
        $em->flush();
    }

}
