<?php

namespace GeneralBundle\Repository;

/**
 * FormaPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormaPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
