<?php

namespace GeneralBundle\Repository;

/**
 * TipoComprobantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoComprobanteRepository extends \Doctrine\ORM\EntityRepository
{
}
