<?php

namespace GeneralBundle\Repository;

/**
 * ValorSugeridoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValorSugeridoRepository extends \Doctrine\ORM\EntityRepository
{
}
