<?php

namespace InventarioBundle\Repository;
use Doctrine\ORM\EntityRepository;


/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends EntityRepository
{
    public function listaDql($strNombre = "", $strCodigo = "") {
        $dql   = "SELECT i FROM InventarioBundle:Articulo i WHERE i.codigoArticuloPk <> 0";        
        if($strCodigo != "") {
            $dql .= " AND i.codigoArticuloPk = " . $strCodigo;
        }
        if($strNombre != "") {
            $dql .= " AND i.nombreArticulo like '%" . $strNombre. "%'";
        }
        $dql .= " ORDER BY i.nombreArticulo ASC";
        
        return $dql;
    } 

           
}
