<?php

namespace InventarioBundle\Repository;
use Doctrine\ORM\EntityRepository;


/**
 * GrupoArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoArticuloRepository extends EntityRepository
{
}
