<?php

namespace InventarioBundle\Repository;

/**
 * GrupoArticulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoArticulosRepository extends \Doctrine\ORM\EntityRepository
{
}
