<?php

namespace InventarioBundle\Repository;

/**
 * MarcaArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcaArticuloRepository extends \Doctrine\ORM\EntityRepository
{
}
