<?php

namespace InventarioBundle\Repository;
use Doctrine\ORM\EntityRepository;


/**
 * MarcaArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcaArticuloRepository extends EntityRepository
{
}
