<?php

namespace InventarioBundle\Repository;

/**
 * MovimientosArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientosArticuloRepository extends \Doctrine\ORM\EntityRepository
{
}
