<?php

namespace InventarioBundle\Repository;

/**
 * SaldosArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaldosArticuloRepository extends \Doctrine\ORM\EntityRepository
{
}
