<?php

namespace InventarioBundle\Repository;

/**
 * UnidadManejoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadManejoRepository extends \Doctrine\ORM\EntityRepository
{
}
